export { inspectTemplate } from "./inspect-template.ts"
export { extractDocumentText, ExtractTextError } from "./extract-document-text.ts"
export { renderTemplate } from "./render-template.ts"
export { templatizeDocument, TemplatizeError } from "./templatize-document.ts"
export { buildTemplateFromSpec } from "./build-template.ts"
export type { DocumentBytes, Placeholder, TemplateInspection } from "./types.ts"
export type { TemplatizeEdit, TemplatizeRun } from "./templatize-document.ts"
export type { BuiltTemplate, TemplateBlock, TemplateGenerationJson } from "./build-template.ts"
